name: 🐛 Bug Report
description: Report something that isn’t working as expected
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting! Please provide as much detail as possible.

  - type: input
    id: title
    attributes:
      label: What’s the bug?
      placeholder: Short summary of the issue
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error
      render: markdown
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
    validations:
      required: false

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - Low
        - Medium
        - High
    validations:
      required: false

assignees:
  - sw
  - sg
  - jw
